
import test from 'node:test';import assert from 'node:assert/strict';import { handleLead } from '../functions/api/lead.js';
const env={SUPABASE_URL:'https://project.supabase.co',SUPABASE_ANON_KEY:'anon',VUD_API_KEY:'key'};
const valid={nom:'Martin',prenom:'Claire',email:'claire@example.fr',tel:'06 12 34 56 78',adresse:'12 rue de Nantes',cp:'44000',ville:'Nantes',projectType:'6 kWc',delais:'2',consent:true,consent_timestamp:'2026-08-04T00:00:00.000Z',submissionId:'submission-44-123456',pageUrl:'https://panneau-solaire-loire-atlantique.fr/devis/'};
const req=(body,origin='https://panneau-solaire-loire-atlantique.fr')=>new Request('https://panneau-solaire-loire-atlantique.fr/api/lead',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json','CF-Connecting-IP':'198.51.100.10'},body:JSON.stringify(body)});
test('refuses non 44 postcode before networking',async()=>{let calls=0;const r=await handleLead({request:req({...valid,cp:'06000'}),env},async()=>{calls++});assert.equal(r.status,400);assert.equal(calls,0)});
test('refuses untrusted origin before networking',async()=>{let calls=0;const r=await handleLead({request:req(valid,'https://evil.test'),env},async()=>{calls++});assert.equal(r.status,403);assert.equal(calls,0)});
test('stores then stops when no buyer',async()=>{const urls=[];const fetcher=async(url)=>{urls.push(url);if(url.includes('submission_id'))return Response.json([]);if(url.includes('rank_rent_leads')&&!url.includes('id=eq'))return Response.json([{id:'lead1'}]);if(url.includes('ping.php'))return Response.json({accept:0,buyers:0});return new Response('',{status:204})};const r=await handleLead({request:req(valid),env},fetcher);const j=await r.json();assert.equal(j.status,'no_buyer');assert.equal(urls.some(u=>u.includes('get.php')),false)});
test('sends after capture and accepted ping',async()=>{const urls=[];const fetcher=async(url)=>{urls.push(url);if(url.includes('submission_id'))return Response.json([]);if(url.includes('rank_rent_leads')&&!url.includes('id=eq'))return Response.json([{id:'lead1'}]);if(url.includes('ping.php'))return Response.json({accept:1,buyers:1});if(url.includes('get.php'))return Response.json({devis_data:{devis_id:'D44'}});return new Response('',{status:204})};const r=await handleLead({request:req(valid),env},fetcher);const j=await r.json();assert.equal(j.status,'sent');assert.equal(j.devisId,'D44')});
test('accepts the Cloudflare Pages production hostname',async()=>{const r=await handleLead({request:req(valid,'https://panneau-solaire-loire-atlantique-fr.pages.dev'),env},async()=>Response.json([{id:'old',vud_status:'sent',vud_devis_id:'DOLD'}]));assert.equal(r.status,200)});
test('uses the server Supabase key when configured',async()=>{const urls=[];const serverEnv={SUPABASE_URL:'https://project.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'server-secret',VUD_API_KEY:'key'};const fetcher=async(url,opt={})=>{urls.push({url,opt});if(url.includes('submission_id')){assert.equal(opt.headers.apikey,'server-secret');return Response.json([{id:'old',vud_status:'sent',vud_devis_id:'DOLD'}])}return new Response('',{status:500})};const r=await handleLead({request:req(valid),env:serverEnv},fetcher);assert.equal(r.status,200);assert.equal(urls.length,1)});
test('duplicate submission is idempotent',async()=>{let calls=0;const fetcher=async()=>{calls++;return Response.json([{id:'old',vud_status:'sent',vud_devis_id:'DOLD'}])};const r=await handleLead({request:req(valid),env},fetcher);const j=await r.json();assert.equal(j.duplicate,true);assert.equal(calls,1)});
