
const SITE_DOMAIN='panneau-solaire-loire-atlantique.fr';
const SITE_NICHE='panneau-solaire';
const DEPT_CODE='44';
const CP_PATTERN=/^44\d{3}$/;
const VUD_PING_URL='https://www.viteundevis.com/api/ping.php';
const VUD_LEAD_URL='https://www.viteundevis.com/api/get.php';
const MAX_BODY_BYTES=16384;
const CONSENT_TEXT='J’accepte d’être contacté(e) par téléphone par ViteUnDevis.com et ses partenaires afin de qualifier ma demande de devis.';
const json=(body,status=200,origin='')=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Access-Control-Allow-Origin':origin||`https://${SITE_DOMAIN}`,'Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type',Vary:'Origin'}});
const allowed=(origin,env)=>origin===`https://${SITE_DOMAIN}`||origin===`https://www.${SITE_DOMAIN}`||origin==='https://panneau-solaire-loire-atlantique-fr.pages.dev'||(env?.ALLOW_LOCAL_ORIGIN==='true'&&/^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/.test(origin));
const phone=(v='')=>{let d=String(v).replace(/\D/g,''); if(d.startsWith('0033'))d='0'+d.slice(4); if(d.startsWith('33')&&d.length===11)d='0'+d.slice(2); return /^0[1-9]\d{8}$/.test(d)?d:null};
const sbHeaders=(env)=>{const key=env.SUPABASE_SERVICE_ROLE_KEY||env.SUPABASE_ANON_KEY;return {'Content-Type':'application/json',apikey:key,Authorization:`Bearer ${key}`}};
const withTimeout=async(url,opt,fetcher)=>{const c=new AbortController();const t=setTimeout(()=>c.abort(),10000);try{return await fetcher(url,{...opt,signal:c.signal})}finally{clearTimeout(t)}};
export async function handleLead({request,env={}},fetcher=fetch){const origin=request.headers.get('Origin')||''; if(!allowed(origin,env))return json({success:false,message:'Origine non autorisée.'},403,origin); if(!env.SUPABASE_URL||!(env.SUPABASE_SERVICE_ROLE_KEY||env.SUPABASE_ANON_KEY)||!env.VUD_API_KEY)return json({success:false,message:'Service non configuré.'},503,origin); if(!request.headers.get('Content-Type')?.includes('application/json'))return json({success:false,message:'Format invalide.'},415,origin); const len=Number(request.headers.get('Content-Length')||0); if(len>MAX_BODY_BYTES)return json({success:false,message:'Requête trop volumineuse.'},413,origin); let raw; try{const text=await request.text(); if(new TextEncoder().encode(text).byteLength>MAX_BODY_BYTES)return json({success:false,message:'Requête trop volumineuse.'},413,origin); raw=JSON.parse(text)}catch{return json({success:false,message:'JSON invalide.'},400,origin)} const clientIp=request.headers.get('CF-Connecting-IP')||''; const consentTimestamp=String(raw.consent_timestamp||'').trim().slice(0,40); const consentUrl=String(raw.pageUrl||'').trim().slice(0,500); if(!clientIp||!consentTimestamp||!consentUrl)return json({success:false,errors:['Preuve de consentement incomplète.']},400,origin); const errors=[]; for(const k of ['nom','prenom','email','tel','adresse','cp','ville','submissionId']) if(!String(raw[k]||'').trim())errors.push(`${k} requis`); if(raw.website)errors.push('Soumission invalide'); if(!CP_PATTERN.test(String(raw.cp||'')))errors.push('Le projet doit être en Loire-Atlantique (44).'); const tel=phone(raw.tel); if(!tel)errors.push('Téléphone invalide'); if(raw.consent!==true)errors.push('Consentement requis'); if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(raw.email||'')))errors.push('Email invalide'); if(errors.length)return json({success:false,errors},400,origin);
 const base=env.SUPABASE_URL.replace(/\/$/,''); const submissionId=String(raw.submissionId); const duplicate=await withTimeout(`${base}/rest/v1/rank_rent_leads?submission_id=eq.${encodeURIComponent(submissionId)}&select=id,vud_status,vud_devis_id`,{headers:sbHeaders(env)},fetcher); if(!duplicate.ok)return json({success:false,message:'Service temporairement indisponible.'},503,origin); const prev=await duplicate.json(); if(prev?.length)return json({success:true,duplicate:true,status:prev[0].vud_status||'captured',devisId:prev[0].vud_devis_id||null},200,origin);
 const description=`Projet panneaux solaires à ${raw.ville} (${raw.cp}) en Loire-Atlantique. Type: ${raw.projectType||'à étudier'}. Délai: ${raw.delais||'non renseigné'}.`; const payload={source_site:SITE_DOMAIN,niche:SITE_NICHE,departement:DEPT_CODE,cat_id:37,cat_name:'Panneaux photovoltaïques',nom:String(raw.nom).trim(),prenom:String(raw.prenom).trim(),email:String(raw.email).trim().toLowerCase(),telephone:tel,adresse:String(raw.adresse).trim(),ville:String(raw.ville).trim(),code_postal:String(raw.cp),description,submission_id:submissionId,page_url:consentUrl,consent_at:consentTimestamp,vud_response:{consent:{date:consentTimestamp,ip:clientIp,text:CONSENT_TEXT,url:consentUrl}},vud_status:'pending'};
 const saved=await withTimeout(`${base}/rest/v1/rank_rent_leads`,{method:'POST',headers:{...sbHeaders(env),Prefer:'return=representation'},body:JSON.stringify(payload)},fetcher); if(!saved.ok)return json({success:false,message:'Enregistrement impossible.'},502,origin); const lead=(await saved.json())?.[0]; const patch=async(data)=>{try{await withTimeout(`${base}/rest/v1/rank_rent_leads?id=eq.${encodeURIComponent(lead.id)}`,{method:'PATCH',headers:sbHeaders(env),body:JSON.stringify({...data,updated_at:new Date().toISOString()})},fetcher)}catch{}};
 let ping; try{ping=await (await withTimeout(VUD_PING_URL,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({token:env.VUD_API_KEY,cat_id:'37',code_postal:String(raw.cp),pays:'fr',description,cpl_mini:'0'})},fetcher)).json()}catch{await patch({vud_status:'ping_error'}); return json({success:true,status:'ping_error'},202,origin)} if(Number(ping.accept)!==1){await patch({vud_status:'no_buyer',vud_ping_buyers:Number(ping.buyers)||0}); return json({success:true,status:'no_buyer'},202,origin)}
 try{const mobile=tel.startsWith('06')||tel.startsWith('07'); const body=new URLSearchParams({key:env.VUD_API_KEY,cat_id:'37',nom:payload.nom,prenom:payload.prenom,email:payload.email,tel:mobile?'':tel,mobile:mobile?tel:'',adresse1:payload.adresse,cp:payload.code_postal,ville:payload.ville,cp_projet:payload.code_postal,ville_projet:payload.ville,pays:'fr',tp:'1',description,site_name:SITE_DOMAIN,format_return:'json',consent_date:consentTimestamp,consent_ip:clientIp,consent_texte:CONSENT_TEXT,consent_url:consentUrl}); const r=await withTimeout(VUD_LEAD_URL,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body},fetcher); const data=await r.json(); const devisId=data?.devis_data?.devis_id||null; await patch({vud_status:devisId?'sent':'captured',vud_devis_id:devisId?String(devisId):null,vud_response:{consent:payload.vud_response.consent,response:data}}); return json({success:true,status:devisId?'sent':'captured',devisId},devisId?200:202,origin)}catch{await patch({vud_status:'captured'}); return json({success:true,status:'captured'},202,origin)} }
export const onRequestOptions=({request,env})=>allowed(request.headers.get('Origin')||'',env)?new Response(null,{status:204,headers:{'Access-Control-Allow-Origin':request.headers.get('Origin')||`https://${SITE_DOMAIN}`,'Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type'}}):json({success:false},403,request.headers.get('Origin')||'');
export const onRequestPost=(context)=>handleLead(context);
export const onRequest=({request})=>json({success:false,message:'Méthode non autorisée.'},405,request.headers.get('Origin')||'');
