import { readdir, readFile, access } from 'node:fs/promises';
import { join, relative, dirname, resolve } from 'node:path';
const dist=new URL('../dist/client/',import.meta.url).pathname;
async function walk(dir){return (await Promise.all((await readdir(dir,{withFileTypes:true})).map(entry=>entry.isDirectory()?walk(join(dir,entry.name)):join(dir,entry.name)))).flat()}
const allFiles=await walk(dist);const htmlFiles=allFiles.filter(file=>file.endsWith('.html'));const existing=new Set(allFiles.map(file=>'/'+relative(dist,file).replace(/\\/g,'/')));const errors=[];const canonicalSeen=new Set();let localCount=0,guideCount=0,imageRefs=0,internalLinks=0;
const strip=(html)=>html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&[a-z#0-9]+;/gi,' ');
const resolves=(href)=>{const clean=href.split('#')[0].split('?')[0];if(!clean)return true;const normalized=clean.startsWith('/')?clean:'/'+clean;const candidates=[normalized,normalized.endsWith('/')?normalized+'index.html':normalized+'.html',normalized.endsWith('/')?normalized.slice(0,-1)+'.html':normalized+'/index.html'];return candidates.some(path=>existing.has(path));};
for(const file of htmlFiles){const html=await readFile(file,'utf8');const route='/'+relative(dist,file).replace(/index\.html$/,'').replace(/\\/g,'/');const title=(html.match(/<title>([\s\S]*?)<\/title>/i)||[])[1];const description=(html.match(/<meta name="description" content="([^"]*)"/i)||[])[1];const canonical=(html.match(/<link rel="canonical" href="([^"]*)"/i)||[])[1];const h1=(html.match(/<h1\b/gi)||[]).length;const words=(strip(html).match(/[A-Za-zÀ-ÿ0-9’'-]+/g)||[]).length;
 if(!title||title.length<20)errors.push(`${route}: title absent ou trop court`);if(!description||description.length<80)errors.push(`${route}: description absente ou trop courte`);if(!canonical)errors.push(`${route}: canonical absent`);if(h1!==1)errors.push(`${route}: ${h1} H1`);if(canonical&&canonicalSeen.has(canonical))errors.push(`${route}: canonical dupliqué`);if(canonical)canonicalSeen.add(canonical);
 if(route.startsWith('/panneau-solaire-')||route.startsWith('/installateur-solaire-')){localCount++;if(words<1200)errors.push(`${route}: page locale trop courte (${words} mots)`);}
 if(route.startsWith('/guides/')&&route!=='/guides/'){guideCount++;if(words<1200)errors.push(`${route}: guide trop court (${words} mots)`);}
 for(const match of html.matchAll(/href="([^"]+)"/g)){const href=match[1];if(href.startsWith('http')||href.startsWith('mailto:')||href.startsWith('tel:')||href.startsWith('#'))continue;internalLinks++;if(!resolves(href))errors.push(`${route}: lien interne cassé ${href}`);}
 for(const match of html.matchAll(/<img[^>]+src="([^"]+)"/g)){const src=match[1];if(src.startsWith('http')||src.startsWith('data:'))continue;imageRefs++;if(!resolves(src))errors.push(`${route}: image absente ${src}`);}
}
if(localCount!==158)errors.push(`Pages locales: ${localCount} au lieu de 158`);if(guideCount!==8)errors.push(`Guides: ${guideCount} au lieu de 8`);if(imageRefs<350)errors.push(`Seulement ${imageRefs} références images`);if(internalLinks<1000)errors.push(`Maillage interne insuffisant: ${internalLinks} liens`);
console.log(`${htmlFiles.length} pages HTML contrôlées · ${localCount} locales · ${guideCount} guides · ${imageRefs} images · ${internalLinks} liens internes.`);if(errors.length){console.error(errors.slice(0,100).join('\n'));process.exit(1)}console.log('Audit SEO, contenu, images et maillage réussi.');
